// Browser-side handle on the compiled shielded-chips contract.
//
// Generated by `yarn new:ui` from
// contract/managed/roulette/compiler/contract-info.json. This file is
// template-owned: change templates/ui/src/midnight/contract.ts, not this copy
// (`yarn new:ui --check <name>` fails CI when they diverge).
//
// examples/shielded-chips/contract/index.ts can't be reused here: it imports
// `node:path` to build an absolute zkConfigPath for NodeZkConfigProvider. The
// compiler's generated JS (contract/managed/roulette/contract/index.js) is
// plain ESM with no Node dependencies, so we import it directly. Run
// `yarn compile` in examples/shielded-chips first; the managed/ output is
// gitignored.
import { CompiledContract } from "@midnight-ntwrk/midnight-js-protocol/compact-js";
import {
  Contract,
  ledger,
  pureCircuits,
  type Ledger,
} from "../../../contract/managed/roulette/contract/index.js";
import { createRoulettePrivateState, rouletteWitnesses as witnesses } from "../../../contract/witnesses.js";
import type { PrivateStateStorage } from "./private-state";

// pureCircuits run locally with no proof and no tx (e.g. deriving a public
// key from a secret to find "which player am I" on the ledger).
export { Contract, ledger, pureCircuits, type Ledger };

/** Every provable circuit, i.e. every ZK key set copy-zk.mjs serves. */
export type ShieldedChipsCircuits = "houseDeposit" | "betColor" | "revealWinningNumber" | "claimWinnings" | "forfeit" | "houseClaimMatch";

/**
 * Private state is whatever examples/shielded-chips/contract/witnesses.ts builds.
 * PRIVATE_STATE_STORAGE below says where it is kept (./private-state.ts).
 */
export type ShieldedChipsPrivateState = ReturnType<typeof createRoulettePrivateState>;
export const createInitialPrivateState = createRoulettePrivateState;
export const PRIVATE_STATE_ID = "shieldedChipsPrivateState";

/**
 * Where private state is kept (`yarn new:ui --private-state`, recorded in
 * ui/new-ui.json): encrypted in IndexedDB,
 * unlocked by a passphrase each session, so it survives reloads.
 */
export const PRIVATE_STATE_STORAGE: PrivateStateStorage = "persistent";

/** Where copy-zk.mjs puts the keys and zkir, relative to the page origin. */
export const ZK_ASSETS_PATH = "managed/roulette";

/**
 * Same construction as CompiledShieldedChipsContract in contract/index.ts:
 *  - withWitnesses: the TypeScript witnesses from contract/witnesses.ts.
 *  - withCompiledFileAssets: required by the type, so the result is a fully
 *    configured CompiledContract. In the browser, midnight-js-contracts gets
 *    verifier/prover keys and ZKIR from `providers.zkConfigProvider`
 *    (a FetchZkConfigProvider pointed at ZK_ASSETS_PATH), not from this path.
 */
export const CompiledShieldedChipsContract = CompiledContract.make(
  "ShieldedChipsContract",
  Contract,
).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets(ZK_ASSETS_PATH),
);
