// yarn report [sim|e2e|all] — runs the acceptance suites and writes one JSON
// report per deliverable under ../reports/, in the shape of mn-examples'
// reports/node-1.0.400-regression.json (subject, run, suites), plus the
// deliverable, its ACs, the gap ids each test covers, and the exact stack.
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { compiler, imageDigests, packages } from '../src/stack.js';

const ROOT = path.resolve(import.meta.dirname, '..', '..');
const layer = process.argv[2] ?? 'all';
const projects = layer === 'all' ? ['sim', 'e2e'] : [layer];

const DELIVERABLES = [
  {
    id: 'SOW-Q3-01',
    title: 'Crypto schemes: ed25519 and ECDSA over P256',
    workspace: 'signature-verify',
    acceptanceCriteria: {
      'AC-1': 'ed25519 signatures can be verified in Compact',
      'AC-2': 'ECDSA signatures over P256 can be verified in Compact',
    },
  },
  {
    id: 'SOW-Q3-03',
    title: 'Multi-contract systems 2: dynamic cross-contract calls',
    workspace: 'dynamic-calls',
    acceptanceCriteria: {
      'AC-1': "a cross-contract call runs the code associated with the callee's address, not just its type",
    },
  },
];

const git = (...args: string[]) => {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return 'unknown';
  }
};

const startedAt = new Date().toISOString();
const stack = { packages: packages(), compiler: compiler(), images: imageDigests() };
const date = startedAt.slice(0, 10);
mkdirSync(path.join(ROOT, 'reports'), { recursive: true });

for (const d of DELIVERABLES) {
  const suites = [];
  for (const project of projects) {
    const out = path.join(ROOT, 'reports', `${d.workspace}.${project}.vitest.json`);
    const run = spawnSync('yarn', ['vitest', 'run', '--project', project, '--reporter=json', `--outputFile=${out}`], {
      cwd: path.join(ROOT, d.workspace),
      stdio: 'inherit',
    });
    let results: { testResults?: Array<{ name: string; assertionResults: Array<{ fullName: string; status: string; duration?: number; failureMessages: string[] }> }> } = {};
    try {
      results = JSON.parse(readFileSync(out, 'utf8'));
    } catch {
      // vitest could not start (e.g. network down for e2e); recorded below
    }
    const tests = (results.testResults ?? []).flatMap((f) =>
      f.assertionResults.map((t) => ({
        file: path.relative(path.join(ROOT, d.workspace), f.name),
        name: t.fullName,
        status: t.status,
        durationMs: Math.round(t.duration ?? 0),
        covers: [...new Set(t.fullName.match(/\b(?:0[13]-G\d+|AC-\d)\b/g) ?? [])],
        ...(t.failureMessages.length ? { failure: t.failureMessages[0]!.split('\n')[0] } : {}),
      })),
    );
    suites.push({
      layer: project,
      exitCode: run.status,
      passed: tests.filter((t) => t.status === 'passed').length,
      failed: tests.filter((t) => t.status === 'failed').length,
      tests,
    });
  }
  const report = {
    $comment: `Foundation acceptance run for ${d.id}, generated by experimental/q3-ledger9 (yarn report ${layer}).`,
    deliverable: d.id,
    title: d.title,
    acceptanceCriteria: d.acceptanceCriteria,
    strategy: 'Foundation SOW3 testing strategy (internal)',
    run: {
      startedAt,
      finishedAt: new Date().toISOString(),
      network: 'local (compose.yml, undeployed)',
      gitCommit: git('rev-parse', '--short', 'HEAD'),
      gitBranch: git('rev-parse', '--abbrev-ref', 'HEAD'),
      workingTree: git('status', '--porcelain', '--', '.') === '' ? 'clean' : 'dirty',
      host: `${process.platform} ${process.arch}, node ${process.version}`,
    },
    stack,
    suites,
  };
  const file = path.join(ROOT, 'reports', `${d.id.toLowerCase()}-local-${date}.json`);
  writeFileSync(file, `${JSON.stringify(report, null, 2)}\n`);
  console.log(`wrote ${path.relative(ROOT, file)}: ${suites.map((s) => `${s.layer} ${s.passed} passed / ${s.failed} failed`).join(', ')}`);
}
