// This file is part of example-private-tip-jar.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file's main purpose is to export the compiled contracts. The example
// ships TWO: private-tip-jar.compact (the tip jar itself) and tip-token.compact
// (a demo faucet that gives the tests shielded coins to tip with). Each compiles
// to its own contract/managed/<name> directory (generated by `yarn compile`,
// gitignored), so each gets its own exports, zk-config path and
// CompiledContract below.
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import path from 'node:path';

export {
  Contract,
  ledger,
  pureCircuits,
  type Witnesses,
  type Ledger,
  type ImpureCircuits,
  type PureCircuits,
} from './managed/private-tip-jar/contract/index.js';
import { Contract } from './managed/private-tip-jar/contract/index.js';
import { witnesses } from './witnesses.js';
const currentDir = path.resolve(new URL(import.meta.url).pathname, '..');
export const zkConfigPath = path.resolve(currentDir, 'managed', 'private-tip-jar');

export const CompiledPrivateTipJarContract = CompiledContract.make(
  'PrivateTipJarContract',
  Contract,
).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets(zkConfigPath),
);

export {
  Contract as TipTokenContract,
  ledger as tipTokenLedger,
  type Ledger as TipTokenLedger,
} from './managed/tip-token/contract/index.js';
import { Contract as TipTokenContractClass } from './managed/tip-token/contract/index.js';
export const tipTokenZkConfigPath = path.resolve(currentDir, 'managed', 'tip-token');

// The demo token declares no witnesses.
export const CompiledTipTokenContract = CompiledContract.make(
  'TipTokenContract',
  TipTokenContractClass,
).pipe(
  CompiledContract.withVacantWitnesses,
  CompiledContract.withCompiledFileAssets(tipTokenZkConfigPath),
);
